-- TODO:
-- add up to 5 player support (for units, just increment the quad by 6 per team after red, likewise increment iconQuad by 28, move this logic to unit.lua, then move the red quad value above super.new)
-- display cost next to unit in the menu
-- add ammo capacity
-- restore fuel and ammo of loaded units
-- finish unloading
-- implement special unit abilities (diving, exploding, etc.)
-- add combat
-- add music
-- add mouse support
-- fix camera