-- TODO:
-- fix layering, it should be in this order (bottom to top) [map -> other units -> tint -> arrow -> moving unit]
-- implement trapping
-- port 5 pre-deployed maps
-- implement supplying (black boat and apc)
-- port 5 3-player maps
-- implement healing (black boat and properties)
-- port 5 4-player maps
-- implement exploding
-- port 5 war-room maps
-- add combat (use range(i,j,range))
-- add destroying pipe seams
-- add music
-- add mouse support
-- fix camera
-- implement fog, including minus icon and fuel cost for fog checking